apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loadbalancerdrivers.lbcf.tke.cloud.tencent.com
spec:
  group: lbcf.tke.cloud.tencent.com
  names:
    kind: LoadBalancerDriver
    listKind: LoadBalancerDriverList
    plural: loadbalancerdrivers
    singular: loadbalancerdriver
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: loadbalancers.lbcf.tke.cloud.tencent.com
spec:
  group: lbcf.tke.cloud.tencent.com
  names:
    kind: LoadBalancer
    listKind: LoadBalancerList
    plural: loadbalancers
    singular: loadbalancer
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backendgroups.lbcf.tke.cloud.tencent.com
spec:
  group: lbcf.tke.cloud.tencent.com
  names:
    kind: BackendGroup
    listKind: BackendGroupList
    plural: backendgroups
    singular: backendgroup
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backendrecords.lbcf.tke.cloud.tencent.com
spec:
  group: lbcf.tke.cloud.tencent.com
  names:
    kind: BackendRecord
    listKind: BackendRecordList
    plural: backendrecords
    singular: backendrecord
  scope: Namespaced
  subresources:
    status: {}
  version: v1beta1
