apiVersion: v1
kind: Service
metadata:
  labels:
  name: lbcf-controller
  namespace: kube-system
spec:
  ports:
    - name: admit-server
      port: 443
      targetPort: 443
    - name: healthz
      port: 11029
      targetPort: 11029
  selector:
    lbcf.tke.cloud.tencent.com/component: lbcf-controller
  sessionAffinity: None
  type: ClusterIP