apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: lbcf-validate
webhooks:
  - name: driver.lbcf.tke.cloud.tencent.com
    rules:
      - apiGroups:
          - "lbcf.tke.cloud.tencent.com"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - loadbalancerdrivers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lJTTlDNlM2cGk0WDR3RFFZSktvWklodmNOQVFFTEJRQXdVREVMTUFrR0ExVUUKQmhNQ1EwNHhLakFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR3RlFZRFZRUUtFdzV6ZVhOMFpXMDZiV0Z6ZEdWeQpjekVWTUJNR0ExVUVBeE1NWTJ4ekxYQnJkRFU0TWpaME1CNFhEVEU1TURVd05qQXpNREEwTjFvWERUTTVNRFV3Ck5qQXpNREEwTjFvd1VERUxNQWtHQTFVRUJoTUNRMDR4S2pBUkJnTlZCQW9UQ25SbGJtTmxiblI1ZFc0d0ZRWUQKVlFRS0V3NXplWE4wWlcwNmJXRnpkR1Z5Y3pFVk1CTUdBMVVFQXhNTVkyeHpMWEJyZERVNE1qWjBNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExVzNuWU5rNk9PVVQ1TnJhTVZCWXNpWkZzOHo5CmFIU3VFakdRK09URVpaNmR0OVQ5K05NMkYzSU9JMGt2NklmL1pjUmk4ZTNqRkpUQmFzQWF0L3liNTJlQzFYbmwKejAzL3BYYUp5NXlSNjJzWnlWZ0hKWkNwR1JoUUR4aGpaaU5TVEtsQWdMdkk2VkZYdzdWS0Y4ZFlkWEwwMWI5Ywp2MUx3UnlMR2s1VnZpY0lnaXloWEdwUWZoUFAwUDE0WHJXUzJDNGhlYjA2a2NpcG1Dd3l3UTlZVVN4NnVuOCtuCmEwU2NzQ1hmd2w4M1dpMFRrbkFsRXlwbStrZ0RvQ1RUbGROUm00QnlicFNhZVM1S05PNzBqTFdTZjNtRmU5aksKeFZuQkdtbjVXWDJqVTcvRW5QZWxWd1Y2UGF5SzJYR3RubnZ0MWQvQXlKNXFkbTRzZWVsSFpmclFRUUlEQVFBQgpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGCkJ3TUJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWx5TzhaSHhIZ3AKRE5mV3k3cmhRUmsrRzJzNUlac0xHc1RMbTVQdHV4Vm5NclN6dGR4TXdPemtaWGFYck1CYjBqZXdYbTdHSEMySwppWnNNV0YwQXZrWUk4OFJMZ1RSWlliYkt3OVpHdTZVOGZ6SHU1dTZHVm80SW9WTUVWSE16RGVmYllFY3VCSkZCCjVTMVpCdVFHV1pHcHBkZU1aL21MOEhqSGVWbTB3VDFGVlYwL0JXc0VJeEp5a09kVmh5L1RmVElVczFwLzBFQ0QKOGtqc3RjejRBaTNQeW9nY2dMWkk2L0RXeFRvRnpibWx2Z0M5OGJuaW0yVnVIQStVQ1dwS0RtNU1sZjQ3ZUtxYQpDeXVpMTJsMEMreWNucGRGY2NzWWV4UkpxY2NzNDg2bkRLNGZWLzg3VkpXS3FoTFpGYWdTTFlWSkdSYjhiM2ZYCis1ZmRJSkRaYytRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      url: "https://10.0.3.16/validateLoadBalancerDriver"
    failurePolicy: Fail
  - name: lb.lbcf.tke.cloud.tencent.com
    rules:
      - apiGroups:
          - "lbcf.tke.cloud.tencent.com"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - loadbalancers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lJTTlDNlM2cGk0WDR3RFFZSktvWklodmNOQVFFTEJRQXdVREVMTUFrR0ExVUUKQmhNQ1EwNHhLakFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR3RlFZRFZRUUtFdzV6ZVhOMFpXMDZiV0Z6ZEdWeQpjekVWTUJNR0ExVUVBeE1NWTJ4ekxYQnJkRFU0TWpaME1CNFhEVEU1TURVd05qQXpNREEwTjFvWERUTTVNRFV3Ck5qQXpNREEwTjFvd1VERUxNQWtHQTFVRUJoTUNRMDR4S2pBUkJnTlZCQW9UQ25SbGJtTmxiblI1ZFc0d0ZRWUQKVlFRS0V3NXplWE4wWlcwNmJXRnpkR1Z5Y3pFVk1CTUdBMVVFQXhNTVkyeHpMWEJyZERVNE1qWjBNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExVzNuWU5rNk9PVVQ1TnJhTVZCWXNpWkZzOHo5CmFIU3VFakdRK09URVpaNmR0OVQ5K05NMkYzSU9JMGt2NklmL1pjUmk4ZTNqRkpUQmFzQWF0L3liNTJlQzFYbmwKejAzL3BYYUp5NXlSNjJzWnlWZ0hKWkNwR1JoUUR4aGpaaU5TVEtsQWdMdkk2VkZYdzdWS0Y4ZFlkWEwwMWI5Ywp2MUx3UnlMR2s1VnZpY0lnaXloWEdwUWZoUFAwUDE0WHJXUzJDNGhlYjA2a2NpcG1Dd3l3UTlZVVN4NnVuOCtuCmEwU2NzQ1hmd2w4M1dpMFRrbkFsRXlwbStrZ0RvQ1RUbGROUm00QnlicFNhZVM1S05PNzBqTFdTZjNtRmU5aksKeFZuQkdtbjVXWDJqVTcvRW5QZWxWd1Y2UGF5SzJYR3RubnZ0MWQvQXlKNXFkbTRzZWVsSFpmclFRUUlEQVFBQgpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGCkJ3TUJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWx5TzhaSHhIZ3AKRE5mV3k3cmhRUmsrRzJzNUlac0xHc1RMbTVQdHV4Vm5NclN6dGR4TXdPemtaWGFYck1CYjBqZXdYbTdHSEMySwppWnNNV0YwQXZrWUk4OFJMZ1RSWlliYkt3OVpHdTZVOGZ6SHU1dTZHVm80SW9WTUVWSE16RGVmYllFY3VCSkZCCjVTMVpCdVFHV1pHcHBkZU1aL21MOEhqSGVWbTB3VDFGVlYwL0JXc0VJeEp5a09kVmh5L1RmVElVczFwLzBFQ0QKOGtqc3RjejRBaTNQeW9nY2dMWkk2L0RXeFRvRnpibWx2Z0M5OGJuaW0yVnVIQStVQ1dwS0RtNU1sZjQ3ZUtxYQpDeXVpMTJsMEMreWNucGRGY2NzWWV4UkpxY2NzNDg2bkRLNGZWLzg3VkpXS3FoTFpGYWdTTFlWSkdSYjhiM2ZYCis1ZmRJSkRaYytRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      url: "https://10.0.3.16/validateLoadBalancer"
    failurePolicy: Fail
  - name: backendgroup.lbcf.tke.cloud.tencent.com
    rules:
      - apiGroups:
          - "lbcf.tke.cloud.tencent.com"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - backendgroups
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lJTTlDNlM2cGk0WDR3RFFZSktvWklodmNOQVFFTEJRQXdVREVMTUFrR0ExVUUKQmhNQ1EwNHhLakFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR3RlFZRFZRUUtFdzV6ZVhOMFpXMDZiV0Z6ZEdWeQpjekVWTUJNR0ExVUVBeE1NWTJ4ekxYQnJkRFU0TWpaME1CNFhEVEU1TURVd05qQXpNREEwTjFvWERUTTVNRFV3Ck5qQXpNREEwTjFvd1VERUxNQWtHQTFVRUJoTUNRMDR4S2pBUkJnTlZCQW9UQ25SbGJtTmxiblI1ZFc0d0ZRWUQKVlFRS0V3NXplWE4wWlcwNmJXRnpkR1Z5Y3pFVk1CTUdBMVVFQXhNTVkyeHpMWEJyZERVNE1qWjBNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExVzNuWU5rNk9PVVQ1TnJhTVZCWXNpWkZzOHo5CmFIU3VFakdRK09URVpaNmR0OVQ5K05NMkYzSU9JMGt2NklmL1pjUmk4ZTNqRkpUQmFzQWF0L3liNTJlQzFYbmwKejAzL3BYYUp5NXlSNjJzWnlWZ0hKWkNwR1JoUUR4aGpaaU5TVEtsQWdMdkk2VkZYdzdWS0Y4ZFlkWEwwMWI5Ywp2MUx3UnlMR2s1VnZpY0lnaXloWEdwUWZoUFAwUDE0WHJXUzJDNGhlYjA2a2NpcG1Dd3l3UTlZVVN4NnVuOCtuCmEwU2NzQ1hmd2w4M1dpMFRrbkFsRXlwbStrZ0RvQ1RUbGROUm00QnlicFNhZVM1S05PNzBqTFdTZjNtRmU5aksKeFZuQkdtbjVXWDJqVTcvRW5QZWxWd1Y2UGF5SzJYR3RubnZ0MWQvQXlKNXFkbTRzZWVsSFpmclFRUUlEQVFBQgpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGCkJ3TUJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWx5TzhaSHhIZ3AKRE5mV3k3cmhRUmsrRzJzNUlac0xHc1RMbTVQdHV4Vm5NclN6dGR4TXdPemtaWGFYck1CYjBqZXdYbTdHSEMySwppWnNNV0YwQXZrWUk4OFJMZ1RSWlliYkt3OVpHdTZVOGZ6SHU1dTZHVm80SW9WTUVWSE16RGVmYllFY3VCSkZCCjVTMVpCdVFHV1pHcHBkZU1aL21MOEhqSGVWbTB3VDFGVlYwL0JXc0VJeEp5a09kVmh5L1RmVElVczFwLzBFQ0QKOGtqc3RjejRBaTNQeW9nY2dMWkk2L0RXeFRvRnpibWx2Z0M5OGJuaW0yVnVIQStVQ1dwS0RtNU1sZjQ3ZUtxYQpDeXVpMTJsMEMreWNucGRGY2NzWWV4UkpxY2NzNDg2bkRLNGZWLzg3VkpXS3FoTFpGYWdTTFlWSkdSYjhiM2ZYCis1ZmRJSkRaYytRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      url: "https://10.0.3.16/validateBackendGroup"
    failurePolicy: Fail
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: lbcf-mutate
webhooks:
  - name: driver.lbcf.tke.cloud.tencent.com
    rules:
      - apiGroups:
          - "lbcf.tke.cloud.tencent.com"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
        resources:
          - loadbalancers
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lJTTlDNlM2cGk0WDR3RFFZSktvWklodmNOQVFFTEJRQXdVREVMTUFrR0ExVUUKQmhNQ1EwNHhLakFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR3RlFZRFZRUUtFdzV6ZVhOMFpXMDZiV0Z6ZEdWeQpjekVWTUJNR0ExVUVBeE1NWTJ4ekxYQnJkRFU0TWpaME1CNFhEVEU1TURVd05qQXpNREEwTjFvWERUTTVNRFV3Ck5qQXpNREEwTjFvd1VERUxNQWtHQTFVRUJoTUNRMDR4S2pBUkJnTlZCQW9UQ25SbGJtTmxiblI1ZFc0d0ZRWUQKVlFRS0V3NXplWE4wWlcwNmJXRnpkR1Z5Y3pFVk1CTUdBMVVFQXhNTVkyeHpMWEJyZERVNE1qWjBNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExVzNuWU5rNk9PVVQ1TnJhTVZCWXNpWkZzOHo5CmFIU3VFakdRK09URVpaNmR0OVQ5K05NMkYzSU9JMGt2NklmL1pjUmk4ZTNqRkpUQmFzQWF0L3liNTJlQzFYbmwKejAzL3BYYUp5NXlSNjJzWnlWZ0hKWkNwR1JoUUR4aGpaaU5TVEtsQWdMdkk2VkZYdzdWS0Y4ZFlkWEwwMWI5Ywp2MUx3UnlMR2s1VnZpY0lnaXloWEdwUWZoUFAwUDE0WHJXUzJDNGhlYjA2a2NpcG1Dd3l3UTlZVVN4NnVuOCtuCmEwU2NzQ1hmd2w4M1dpMFRrbkFsRXlwbStrZ0RvQ1RUbGROUm00QnlicFNhZVM1S05PNzBqTFdTZjNtRmU5aksKeFZuQkdtbjVXWDJqVTcvRW5QZWxWd1Y2UGF5SzJYR3RubnZ0MWQvQXlKNXFkbTRzZWVsSFpmclFRUUlEQVFBQgpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGCkJ3TUJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWx5TzhaSHhIZ3AKRE5mV3k3cmhRUmsrRzJzNUlac0xHc1RMbTVQdHV4Vm5NclN6dGR4TXdPemtaWGFYck1CYjBqZXdYbTdHSEMySwppWnNNV0YwQXZrWUk4OFJMZ1RSWlliYkt3OVpHdTZVOGZ6SHU1dTZHVm80SW9WTUVWSE16RGVmYllFY3VCSkZCCjVTMVpCdVFHV1pHcHBkZU1aL21MOEhqSGVWbTB3VDFGVlYwL0JXc0VJeEp5a09kVmh5L1RmVElVczFwLzBFQ0QKOGtqc3RjejRBaTNQeW9nY2dMWkk2L0RXeFRvRnpibWx2Z0M5OGJuaW0yVnVIQStVQ1dwS0RtNU1sZjQ3ZUtxYQpDeXVpMTJsMEMreWNucGRGY2NzWWV4UkpxY2NzNDg2bkRLNGZWLzg3VkpXS3FoTFpGYWdTTFlWSkdSYjhiM2ZYCis1ZmRJSkRaYytRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      url: "https://10.0.3.16/mutateLoadBalancer"
    failurePolicy: Fail
  - name: driver.lbcf.tke.cloud.tencent.com
    rules:
      - apiGroups:
          - "lbcf.tke.cloud.tencent.com"
        apiVersions:
          - v1beta1
        operations:
          - CREATE
        resources:
          - backendgroups
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURaRENDQWt5Z0F3SUJBZ0lJTTlDNlM2cGk0WDR3RFFZSktvWklodmNOQVFFTEJRQXdVREVMTUFrR0ExVUUKQmhNQ1EwNHhLakFSQmdOVkJBb1RDblJsYm1ObGJuUjVkVzR3RlFZRFZRUUtFdzV6ZVhOMFpXMDZiV0Z6ZEdWeQpjekVWTUJNR0ExVUVBeE1NWTJ4ekxYQnJkRFU0TWpaME1CNFhEVEU1TURVd05qQXpNREEwTjFvWERUTTVNRFV3Ck5qQXpNREEwTjFvd1VERUxNQWtHQTFVRUJoTUNRMDR4S2pBUkJnTlZCQW9UQ25SbGJtTmxiblI1ZFc0d0ZRWUQKVlFRS0V3NXplWE4wWlcwNmJXRnpkR1Z5Y3pFVk1CTUdBMVVFQXhNTVkyeHpMWEJyZERVNE1qWjBNSUlCSWpBTgpCZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUExVzNuWU5rNk9PVVQ1TnJhTVZCWXNpWkZzOHo5CmFIU3VFakdRK09URVpaNmR0OVQ5K05NMkYzSU9JMGt2NklmL1pjUmk4ZTNqRkpUQmFzQWF0L3liNTJlQzFYbmwKejAzL3BYYUp5NXlSNjJzWnlWZ0hKWkNwR1JoUUR4aGpaaU5TVEtsQWdMdkk2VkZYdzdWS0Y4ZFlkWEwwMWI5Ywp2MUx3UnlMR2s1VnZpY0lnaXloWEdwUWZoUFAwUDE0WHJXUzJDNGhlYjA2a2NpcG1Dd3l3UTlZVVN4NnVuOCtuCmEwU2NzQ1hmd2w4M1dpMFRrbkFsRXlwbStrZ0RvQ1RUbGROUm00QnlicFNhZVM1S05PNzBqTFdTZjNtRmU5aksKeFZuQkdtbjVXWDJqVTcvRW5QZWxWd1Y2UGF5SzJYR3RubnZ0MWQvQXlKNXFkbTRzZWVsSFpmclFRUUlEQVFBQgpvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdJR0NDc0dBUVVGCkJ3TUJNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRWx5TzhaSHhIZ3AKRE5mV3k3cmhRUmsrRzJzNUlac0xHc1RMbTVQdHV4Vm5NclN6dGR4TXdPemtaWGFYck1CYjBqZXdYbTdHSEMySwppWnNNV0YwQXZrWUk4OFJMZ1RSWlliYkt3OVpHdTZVOGZ6SHU1dTZHVm80SW9WTUVWSE16RGVmYllFY3VCSkZCCjVTMVpCdVFHV1pHcHBkZU1aL21MOEhqSGVWbTB3VDFGVlYwL0JXc0VJeEp5a09kVmh5L1RmVElVczFwLzBFQ0QKOGtqc3RjejRBaTNQeW9nY2dMWkk2L0RXeFRvRnpibWx2Z0M5OGJuaW0yVnVIQStVQ1dwS0RtNU1sZjQ3ZUtxYQpDeXVpMTJsMEMreWNucGRGY2NzWWV4UkpxY2NzNDg2bkRLNGZWLzg3VkpXS3FoTFpGYWdTTFlWSkdSYjhiM2ZYCis1ZmRJSkRaYytRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      url: "https://10.0.3.16/mutateBackendGroup"
    failurePolicy: Fail
